# Generated by Django 3.0.8 on 2020-08-03 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='submit_date',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='update_date',
        ),
    ]
