# Generated by Django 3.0.8 on 2020-08-03 20:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20200803_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='submit_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 8, 3, 20, 23, 4, 189778, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
