# Generated by Django 3.0.8 on 2020-08-04 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20200804_0355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-submit_date']},
        ),
    ]
